- name: delete user
  hosts: all
  ignore_errors: yes
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  vars_files:
    - vars.yml
  tasks:
    - name: delete user
      vars:
        - ansible_command_timeout: 60
      arubaoss_command:
        commands:
          - configure terminal
          - no password operator
