- name: delete vlan
  hosts: all
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  vars_files:
    - vars.yml
  tasks:
    - name: Remove VLAN
      arubaoss_command:
        commands:
          - configure terminal
          - no vlan 500
