- name: disable http
  hosts: all
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  vars_files:
    - vars.yml
  tasks:
    - name: Disable HTTP
      arubaoss_command:
        commands:
          - no http
          #          - https-server session close all
          #   - ip http secure-server
          #- no ip http server
